
CREATE TABLE cursos (
      id INT AUTO_INCREMENT PRIMARY KEY
    , image VARCHAR(255) NOT NULL
    , title VARCHAR(255) NOT NULL
    , description TEXT
    , url_video TEXT
    , created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
